# run as login shell (to source .rc files)
shell:
  program: /bin/bash
  args:
    - --login

# this font looks good on my shitty thinkpad screen
font:
  size: 11
  normal:
    family: Input
    style: Regular
  bold:
    family: Input
    style: Bold
  italic:
    family: Input
    style: Italic

# (gruvbox - dark)
colors:
  # default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

# (papercolor - light)
# colors:
#   primary:
#     background: '0xEEEEEE'
#     foreground: '0x4D4D4C'
#   normal:
#     black:   '0xEDEDED'
#     red:     '0xD7005F'
#     green:   '0x718C00'
#     yellow:  '0xD75F00'
#     blue:    '0x4271AE'
#     magenta: '0x8959A8'
#     cyan:    '0x3E999F'
#     white:   '0x4D4D4C'

#   bright:
#     black:   '0x969694'
#     red:     '0xD7005F'
#     green:   '0x718C00'
#     yellow:  '0xD75F00'
#     blue:    '0x4271AE'
#     magenta: '0x8959A8'
#     cyan:    '0x3E999F'
#     white:   '0xF5F5F5'
