#!/usr/bin/env bash

function menu () {
    echo "configs: a simple script that installs my hardware configs."
    echo ""
    echo "  ./configs help     -prints out all configs"
    echo "  ./configs install  -installs configs"
}


function help () {
    echo "configs"
    echo ""
    echo "  keyboard-repeat     -sets keypress repeat to max"
    echo "  caps-to-ctrl        -maps ctrl to caps lock"
    exit 0
}

function install () {
  ./hardware/keyboard-repeat
  ./hardware/caps-to-ctrl
  echo "complete. some changes require logout to take place"
  exit 0
}


[[ $1 = "install" ]] && install
[[ $1 = "help" ]] && help
menu
