#!/usr/bin/env bash

function menu () {
    echo "dotfiles: a simple script that installs my dotfiles & configs."
    echo ""
    echo "  ./dotfiles help     -prints out all configs"
    echo "  ./dotfiles install  -installs configs" 
}


function help () {
    echo "configs"
    echo ""
    echo "  keyboard-repeat     -sets keypress repeat to max"
    echo "  caps-to-ctrl        -maps ctrl to caps lock"
    exit 0 
}

function install () {
  cp dotfiles/.bash_profile $HOME
  cp dotfiles/.gitconfig $HOME
  cp dotfiles/.vimrc $HOME
  ./hardware/keyboard-repeat
  ./hardware/caps-to-ctrl
  echo "complete. some changes require logout to take place"
  exit 0
}


[[ $1 = "install" ]] && install
[[ $1 = "help" ]] && help
menu
