#!/usr/bin/env bash

function menu () {
    echo "make-life-easy: a simple script that installs my dotfiles & configs."
    echo ""
    echo "   ./easy help         -prints out all configs that make-life-easy implements"
    echo "   ./easy init         -installs configs" 
}


function help () {
    echo "configs"
    echo ""
    echo "    keyboard-repeat    -sets keypress repeat to max"
    echo "    caps-to-ctrl       -maps ctrl to caps lock"
    exit 0 
}

function init () {
  cp .bash_profile $HOME
  cp .gitconfig $HOME
  cp .vimrc $HOME
  ./keyboard-repeat
  ./caps-to-ctrl
  echo "complete. some changes require logout to take place"
  exit 0
}


[[ $1 = "init" ]] && init
[[ $1 = "help" ]] && help
menu
