# visual
theme = "github_mod"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# config
[editor]
auto-pairs = true 
auto-completion = false
bufferline = "always"
text-width = 100

[editor.statusline]
left = ["mode", "spinner", "file-absolute-path", "read-only-indicator", "file-modification-indicator"]

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true

# remaps
[keys.normal]
C-c = ["keep_primary_selection", "collapse_selection"]
g.c = "toggle_comments"
space.e = "file_picker_in_current_buffer_directory"
# space.o = ":sh gh repo view --web"

[keys.select]
C-c = "normal_mode" 

[keys.insert]
C-c = ["normal_mode", "keep_primary_selection", "collapse_selection"]
