[[language]]
name = "vcl"
scope = "source.vcl"
injection-regex = "vcl"
file-types = ["vcl"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
roots = []
grammar = "python"

[[language]]
name = "styri"
scope = "source.sy"
injection-regex = "sy"
file-types = ["sy"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
roots = []
grammar = "python"
